function addDays(dateStr, days) {
  const d = new Date(dateStr);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

const CITY_META = {
  'Санкт-Петербург': {
    country: 'Россия',
    image: 'https://images.unsplash.com/photo-1548834925-e48f8a27d7b2?w=1200',
    places: [
      {
        id: 'p1',
        name: 'Эрмитаж',
        category: 'Музей',
        emoji: '🏛️',
        description: 'Крупнейший музейный комплекс России.',
        duration: '3-4 часа',
        time: '10:00',
        rating: 4.9,
        address: 'Дворцовая площадь, 2',
        price: '500 ₽',
      },
      {
        id: 'p2',
        name: 'Разводные мосты',
        category: 'Вечерняя программа',
        emoji: '🌉',
        description: 'Ночная прогулка по Неве.',
        duration: '2 часа',
        time: '21:00',
        rating: 4.8,
        address: 'Дворцовая набережная',
        price: 'Бесплатно',
      },
    ],
    hotel: { name: 'Nevsky Grand Hotel', price: 7200 },
  },
  Москва: {
    country: 'Россия',
    image: 'https://images.unsplash.com/photo-1513326738677-b964603b136d?w=1200',
    places: [
      {
        id: 'p1',
        name: 'Красная площадь',
        category: 'История',
        emoji: '🧱',
        description: 'Сердце столицы.',
        duration: '2 часа',
        time: '10:00',
        rating: 4.9,
        address: 'Красная площадь',
        price: 'Бесплатно',
      },
      {
        id: 'p2',
        name: 'Москва-Сити',
        category: 'Архитектура',
        emoji: '🏙️',
        description: 'Смотровая площадка с панорамой города.',
        duration: '2 часа',
        time: '18:00',
        rating: 4.7,
        address: 'Пресненская набережная',
        price: '1 200 ₽',
      },
    ],
    hotel: { name: 'Marriott Moscow', price: 12500 },
  },
  Казань: {
    country: 'Россия',
    image: 'https://images.unsplash.com/photo-1595218699680-e9c3acba6e91?w=1200',
    places: [
      {
        id: 'p1',
        name: 'Казанский Кремль',
        category: 'История',
        emoji: '🏰',
        description: 'Исторический центр Казани.',
        duration: '2-3 часа',
        time: '10:30',
        rating: 4.8,
        address: 'Кремль',
        price: '200 ₽',
      },
      {
        id: 'p2',
        name: 'Улица Баумана',
        category: 'Прогулка',
        emoji: '🛍️',
        description: 'Пешеходная улица с кафе и сувенирами.',
        duration: '2 часа',
        time: '15:00',
        rating: 4.6,
        address: 'ул. Баумана',
        price: 'Бесплатно',
      },
    ],
    hotel: { name: 'Korston Kazan', price: 6800 },
  },
  Сочи: {
    country: 'Россия',
    image: 'https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=1200',
    places: [
      {
        id: 'p1',
        name: 'Роза Хутор',
        category: 'Природа',
        emoji: '🏔️',
        description: 'Горный курорт с канатной дорогой.',
        duration: '5 часов',
        time: '09:30',
        rating: 4.8,
        address: 'Роза Хутор',
        price: '2 000 ₽',
      },
      {
        id: 'p2',
        name: 'Набережная Сочи',
        category: 'Прогулка',
        emoji: '🌊',
        description: 'Вечер у моря.',
        duration: '2 часа',
        time: '19:00',
        rating: 4.7,
        address: 'Центральная набережная',
        price: 'Бесплатно',
      },
    ],
    hotel: { name: 'Sea Galaxy Hotel', price: 8400 },
  },
  Калининград: {
    country: 'Россия',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200',
    places: [
      {
        id: 'p1',
        name: 'Остров Канта',
        category: 'История',
        emoji: '⛪',
        description: 'Кафедральный собор и музейная зона.',
        duration: '2 часа',
        time: '11:00',
        rating: 4.7,
        address: 'Остров Канта',
        price: '300 ₽',
      },
      {
        id: 'p2',
        name: 'Рыбная деревня',
        category: 'Еда',
        emoji: '🐟',
        description: 'Рестораны и набережная.',
        duration: '2 часа',
        time: '18:30',
        rating: 4.6,
        address: 'Октябрьский остров',
        price: '1 300 ₽',
      },
    ],
    hotel: { name: 'Kaliningrad Hotel', price: 5900 },
  },
  Владивосток: {
    country: 'Россия',
    image: 'https://images.unsplash.com/photo-1601462904263-f2fa0c851cb9?w=1200',
    places: [
      {
        id: 'p1',
        name: 'Токаревский маяк',
        category: 'Природа',
        emoji: '🗼',
        description: 'Символ Владивостока у Японского моря.',
        duration: '1.5 часа',
        time: '10:30',
        rating: 4.8,
        address: 'Токаревская кошка',
        price: 'Бесплатно',
      },
      {
        id: 'p2',
        name: 'Русский мост',
        category: 'Архитектура',
        emoji: '🌉',
        description: 'Видовые точки на остров Русский.',
        duration: '2.5 часа',
        time: '15:30',
        rating: 4.7,
        address: 'Русский мост',
        price: 'Бесплатно',
      },
    ],
    hotel: { name: 'Azimut Vladivostok', price: 7600 },
  },
  Байкал: {
    country: 'Россия',
    image: 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=1200',
    places: [
      {
        id: 'p1',
        name: 'Листвянка',
        category: 'Природа',
        emoji: '🏞️',
        description: 'Берег Байкала и рынок сувениров.',
        duration: '4 часа',
        time: '10:00',
        rating: 4.9,
        address: 'Листвянка',
        price: '1 000 ₽',
      },
      {
        id: 'p2',
        name: 'Кругобайкальская прогулка',
        category: 'Активности',
        emoji: '🥾',
        description: 'Треккинг вдоль берега.',
        duration: '3 часа',
        time: '16:00',
        rating: 4.8,
        address: 'Южный Байкал',
        price: '1 500 ₽',
      },
    ],
    hotel: { name: 'Baikal View Hotel', price: 9400 },
  },
};

function createTrip({ id, from, to, startDate, status, budget, travelers, travelStyle, interests }) {
  const meta = CITY_META[to];
  const endDate = addDays(startDate, 3);
  const nights = 3;
  const totalTransport = Math.round(budget * 0.2);
  const totalHotel = meta.hotel.price * nights;
  const totalActivities = Math.round(budget * 0.2);
  const totalFood = Math.round(budget * 0.18);

  return {
    id,
    from,
    to,
    toCountry: meta.country,
    startDate,
    endDate,
    budget,
    currency: '₽',
    travelers,
    interests,
    travelStyle,
    status,
    coverImage: meta.image,
    days: [
      {
        day: 1,
        date: 'День 1',
        places: meta.places,
      },
    ],
    transport: [
      {
        id: `${id}-t1`,
        type: 'flight',
        from,
        to,
        departure: '08:40',
        arrival: '11:20',
        duration: '2 ч 40 мин',
        price: Math.round(totalTransport * 0.55),
        carrier: 'Аэрофлот',
        class: travelStyle === 'luxury' ? 'Бизнес' : 'Эконом',
      },
      {
        id: `${id}-t2`,
        type: 'train',
        from: to,
        to: from,
        departure: '18:30',
        arrival: '07:10',
        duration: '12 ч 40 мин',
        price: Math.round(totalTransport * 0.45),
        carrier: 'РЖД',
        class: 'Купе',
      },
    ],
    hotels: [
      {
        id: `${id}-h1`,
        name: meta.hotel.name,
        stars: 4,
        rating: 4.6,
        reviews: 1300,
        pricePerNight: meta.hotel.price,
        distanceFromCenter: '0.8 км',
        address: `${to}, центр`,
        amenities: ['WiFi', 'Завтрак', 'Фитнес'],
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900',
      },
    ],
    totalTransport,
    totalHotel,
    totalActivities,
    totalFood,
  };
}

function buildDemoTrips() {
  return [
    createTrip({
      id: 'api-seed-spb-1',
      from: 'Москва',
      to: 'Санкт-Петербург',
      startDate: '2026-05-10',
      status: 'upcoming',
      budget: 52000,
      travelers: 2,
      travelStyle: 'standard',
      interests: ['museums', 'food'],
    }),
    createTrip({
      id: 'api-seed-kzn-1',
      from: 'Москва',
      to: 'Казань',
      startDate: '2026-05-22',
      status: 'upcoming',
      budget: 48000,
      travelers: 2,
      travelStyle: 'standard',
      interests: ['history', 'food'],
    }),
    createTrip({
      id: 'api-seed-sochi-1',
      from: 'Казань',
      to: 'Сочи',
      startDate: '2026-06-03',
      status: 'upcoming',
      budget: 76000,
      travelers: 2,
      travelStyle: 'comfort',
      interests: ['beach', 'nature'],
    }),
    createTrip({
      id: 'api-seed-kgd-1',
      from: 'Москва',
      to: 'Калининград',
      startDate: '2026-06-16',
      status: 'upcoming',
      budget: 56000,
      travelers: 2,
      travelStyle: 'comfort',
      interests: ['history', 'food'],
    }),
    createTrip({
      id: 'api-seed-vvo-1',
      from: 'Москва',
      to: 'Владивосток',
      startDate: '2026-07-01',
      status: 'upcoming',
      budget: 92000,
      travelers: 2,
      travelStyle: 'comfort',
      interests: ['nature', 'food'],
    }),
    createTrip({
      id: 'api-seed-baikal-1',
      from: 'Москва',
      to: 'Байкал',
      startDate: '2026-07-20',
      status: 'upcoming',
      budget: 104000,
      travelers: 2,
      travelStyle: 'comfort',
      interests: ['nature', 'hiking'],
    }),
    createTrip({
      id: 'api-seed-msk-past',
      from: 'Казань',
      to: 'Москва',
      startDate: '2025-04-10',
      status: 'past',
      budget: 42000,
      travelers: 1,
      travelStyle: 'standard',
      interests: ['history'],
    }),
    createTrip({
      id: 'api-seed-spb-past',
      from: 'Москва',
      to: 'Санкт-Петербург',
      startDate: '2025-08-14',
      status: 'past',
      budget: 46000,
      travelers: 2,
      travelStyle: 'standard',
      interests: ['museums'],
    }),
    createTrip({
      id: 'api-seed-kzn-draft',
      from: 'Москва',
      to: 'Казань',
      startDate: '2026-08-12',
      status: 'draft',
      budget: 36000,
      travelers: 1,
      travelStyle: 'budget',
      interests: ['food'],
    }),
  ];
}

module.exports = { buildDemoTrips };

